---
title: "How I make the most<br>of a One-Off Workshop"
author: "Clay Ford"
date: "Spring 2022"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Traditional Teaching at UVA

>- Instructors can get to know students, see them 2-3 times/week for 16 weeks.
>- There is time for repeated assessments.
>- Instructors get second chances to review material, catch up on missed material, redeem themselves after an "off day".
>- There is college credit at stake. The class costs money. Which means...
>- The instructor has authority and students are invested.
>- Hard to drop out after a couple of weeks.

## One-off Library Workshop at UVA

>- See students once for 60 - 90 minutes; don’t get to know them.
>- There are no repeated assessments.
>- There is no second chance to catch up on missed materials or make adjustments.
>- There is no college credit at stake. The class is free. Which means...
>- The teacher-student dynamic isn’t there. The “students” are sometimes faculty, staff, colleagues or community members.
>- People can just leave, drop off Zoom, or not show at all.

## How I make the most of a one-off Workshop

>- Prepare and rehearse my introduction. Keep it short and get to the subject matter.
>- don’t have everyone introduce themselves. 
>- send a pre-workshop email to help students prepare for the workshop (eg, install software, download data, create account) 
>- check for late registrations the day of workshop and send them my pre-workshop email. 
>- Create self-contained workshop materials suitable for self-study and make them publicly available.

## More things I do

>- Don't wing it. Have a script or good notes. Rehearse. 
>- When teaching software, I try to make sure I have the same version as the newest students. 
>- Hot take: I'm not a fan of Zoom breakout rooms.
>- Started doing exercises together as a class instead of pausing for independent work. 
>- Use a pre-workshop checklist. [Here's the latest version](https://github.com/clayford/workshop_checklist/blob/main/README.md)
>- I'm not afraid to start a little late, but I end on time or early.

## Done!

Thanks to Jenny Coffman for inviting me and encouraging me to speak.





